# Default values for Edgex.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


expose:
  # Option value: ClusterIP/NodePort/LoadBalancer
  type: NodePort
  nodePort:
    core:
      data: 32767
      metadata: 30081
      command: 30082
    support:
      scheduler: 30085
    device:
      virtual: 31990
      sensors: 31995 
      sensors1: 31988
    application: 
      operational: 31997
      process: 31999
    ui: 32000

# edgex defines a set of configuration properties for application-level concerns
edgex:
  # app defines a single point in naming/referring to an application. For each application, the value
  # define its label name, resource name or base of the resource name, and service name.
  app:
    core:
      command: edgex-core-command
      data: edgex-core-data
      metadata: edgex-core-metadata
    support:
      scheduler: edgex-support-scheduler
    device:
      virtual: edgex-device-virtual
      sensors: edgex-sensors
    redis: redis-redis-ha-haproxy.redis
    application: 
      operational: edgex-application-operational
      process: edgex-application-process
    ui: edgex-ui-go
  # image defines configuration properties for docker-image-level concerns
  image:
    core:
      command:
        repository: edgexfoundry/docker-core-command-go
        tag: 1.3.0
        pullPolicy: IfNotPresent
      data:
        repository: edgexfoundry/docker-core-data-go
        tag: 1.3.0
        pullPolicy: IfNotPresent
      metadata:
        repository: edgexfoundry/docker-core-metadata-go
        tag: 1.3.0
        pullPolicy: IfNotPresent
    support:
      scheduler:
        repository: edgexfoundry/docker-support-scheduler-go
        tag: 1.3.0
        pullPolicy: IfNotPresent
    device:
      virtual:
        repository: edgexfoundry/docker-device-virtual-go
        tag: 1.3.0
        pullPolicy: IfNotPresent
      sensors:
        repository: conceptreplyit/machine-data-collection
        tag: 0.1.4
        pullPolicy: IfNotPresent
      sensorsamada:
        repository: conceptreplyit/machine-data-collection
        tag: 0.1.4
        pullPolicy: IfNotPresent
    application:
      operational:
        repository: conceptreplyit/export-operational-data
        tag: 0.1.2
        pullPolicy: IfNotPresent
      process:
        repository: conceptreplyit/export-process-data
        tag: 0.1.3
        pullPolicy: IfNotPresent
    ui:
      repository: edgexfoundry/docker-edgex-ui-go
      tag: 1.3.0
      pullPolicy: IfNotPresent
  
  # replicas defines the number of replicas in a Deployment for the respective application
  replicas:
    core:
      command: 1
      data: 1
      metadata: 1
    support:
      scheduler: 1
    device:
      virtual: 1
      sensors: 0
    application:
      operational: 0
      process: 0
    ui: 1
  # resources defines the cpu and memory limits and requests for the respective application
  resources:
    core:
      command:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      data:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      metadata:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
    support:
      scheduler:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
    device:
      virtual:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 200Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      sensors:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
    application:
      operational:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
      process:
        enforceLimits: false
        limits:
          cpu: 1
          memory: 512Mi
        requests:
          cpu: 0.5
          memory: 256Mi
rbac:
  # Specifies whether RBAC resources should be created
  create: true

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name:
